DATA:
    DIR: "data/training/"
    VAL_DIR: "data/training/"
    TEST_DIR: "data/"
    LABEL_FILE: "data/training/train.txt"
    VAL_LABEL_FILE: "data/training/test.txt"
    TEST_LABEL_FILE: "data/sel_test.txt"
    #DIR: "data/training/"
    #VAL_DIR: "data/training/"
    #TEST_DIR: "data/training/"
    #LABEL_FILE: "data/training/train_1716_100_100.txt"
    #VAL_LABEL_FILE: "data/training/test_1716_100_100.txt"
    #TEST_LABEL_FILE: "data/training/test_1716_100_100.txt"
    BATCH_SIZE: 8
    WORKERS: 2

OPTIMIZER:
    LR: 2e-4
    MOMENTUM: 0.9
    GAMMA: 0.1
    WEIGHT_DECAY: 0
    STEPS: []

MODEL:
    NUMANGLE: 100
    NUMRHO: 100
    FIX: True
    THRESHOLD: 0.01
    EDGE_ALIGN: False
    BACKBONE: resnet50 
    # only support : resnet18, resnet50, resnet101, mobilenetv2, resnext50, res2net50, vgg16

TRAIN:
    EPOCHS: 60
    PRINT_FREQ: 100
    TEST: False
    SEED: 1997
    GPU_ID: 0
    DATA_PARALLEL: False
    RESUME: 

MISC:
    TMP: "./result/reproduce"
